name: automate
on:
  schedule:
    - cron: "0 3 * * *" #日本時間で毎日正午に実行する
  push:
    branches: ["**"]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  get_diff_and_post:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Create dot env file
      - shell: bash
      run: |
        touch .env
        echo "FOO=${{ secrets.BOT_PRIVATE_KEY_HEX }}" >> .env

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: python -m pip install -r requirements.txt

      - name: Get Diff Text
        run: python ./src/py/main.py
        timeout-minutes: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Install Dependencies
        run: npm install
      
      - name: Post to Nostr
        run: npx ts-node ./src/ts/index.ts
        timeout-minutes: 2